# ML-03 — Frame Your Lane as an ML Task

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/vxsnth/Machine_learning/blob/main/work/notebooks/w02_ml_task_framing.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

### My lane as an ML task

I am framing my lane as a ranking task. The goal is to rank content pages by their priority for human review. The output would be an ordered list, with pages that appear more likely to deserve attention near the top. Ranking fits the decision because the content team has limited review time and needs to know which pages to look at first.

In [13]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

### Target or proxy

I would predict a page-level `review_priority` proxy. This represents how strongly the observed data suggests that a page should be considered for human review.

The ideal target would be an observed outcome showing whether a page was actually worth reviewing or whether a refresh led to a useful outcome. The starter data does not provide that direct label, so this is a defined proxy rather than an observed outcome.

The proxy represents review priority, not a guaranteed refresh recommendation. The model would support human review rather than automatically deciding what should be changed.

In [14]:

target_sketch = df[
    ["content_id", "impressions_90d", "trend_direction"]
].head(4).copy()

target_sketch["review_priority"] = "to_be_defined"

target_sketch

             content_id  impressions_90d trend_direction review_priority
0  content_304f48230142             3803            down   to_be_defined
1  content_a1fb4e703a9e            15320            down   to_be_defined
2  content_9aa793d4d895            12581            down   to_be_defined
3  content_331d6c4de07b            11751          stable   to_be_defined

### Success metric

I would use Precision@50 as the main success metric. This measures how many of the top 50 pages selected by the ranking are actually positive review candidates according to the chosen target or proxy.

This metric matches the real decision because a content team cannot review every page. The goal is to make the top of the review queue useful, rather than simply getting a high overall accuracy score.

In [15]:
# The intended review queue size for evaluation
k = 50

print("Evaluation metric: Precision@50")
print("Top pages evaluated:", k)

Evaluation metric: Precision@50
Top pages evaluated: 50

### The unit of analysis

One row = one content page. Each page is identified by `content_id`. I am using page-level signals because my decision is also page-level: which content pages should a content team review first.

In [16]:
import pandas as pd

# Load the starter dataset
url = "https://raw.githubusercontent.com/vxsnth/Machine_learning/main/data/raw/content_refresh_anonymized.csv"

df = pd.read_csv(url)

print("Rows:", len(df))
print("Columns:", len(df.columns))

# Show 4 real content pages
page_slice = df[
    ["content_id", "impressions_90d", "trend_direction"]
].head(4)

page_slice

Rows: 30000
Columns: 44

             content_id  impressions_90d trend_direction
0  content_304f48230142             3803            down
1  content_a1fb4e703a9e            15320            down
2  content_9aa793d4d895            12581            down
3  content_331d6c4de07b            11751          stable

In [17]:
print("Rows shown:", len(page_slice))
print("Unique content pages shown:", page_slice["content_id"].nunique())

Rows shown: 4
Unique content pages shown: 4

### Why ML beats a fixed rule here

A fixed rule could rank pages using one threshold, such as reviewing every page whose impressions are below a chosen value. That would be simple and easy to explain, but it would ignore the fact that several page-level signals may matter at the same time.

For example, a page with lower impressions may still be worth protecting, while another page with higher impressions may show signals that make it a stronger review candidate. A ranking model can combine multiple observed signals and learn patterns associated with the target or proxy.

I would still compare the ML ranking with a simple rule-based baseline. ML is useful only if it provides better decision support than that simpler approach.

In [18]:

threshold = df["impressions_90d"].median()

rule_candidates = df[
    df["impressions_90d"] < threshold
]

print("Simple rule: review pages below median 90-day impressions")
print("Threshold:", threshold)
print("Pages selected:", len(rule_candidates))

Simple rule: review pages below median 90-day impressions
Threshold: 731.0
Pages selected: 14993

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.